sudo: required
services:
  - docker
before_install:
  - docker build -t gauravverma029/docker-react -f Dockerfile .
script:
  - docker run -e CI=true gauravverma029/docker-react npm run test -- --coverage
